[main]
font=JetBrainsMono Nerd Font:size=16
prompt="󰍉 "
placeholder=Search...
anchor=center
# y-margin=8
width=40
lines=12
horizontal-pad=16
vertical-pad=8
inner-pad=6
dpi-aware=no
layer=overlay
icons-enabled=yes
icon-theme=hicolor
match-mode=fzf
sort-result=yes
show-actions=no
terminal=ghostty -e

# [colors]
include=~/.config/fuzzel/themes/catppuccin-mocha/blue.ini

[border]
width=1
radius=4
selection-radius=4
